
[LegalNotice]
Accepted=true

[BitTorrent]
Session\DefaultSavePath=/staging/downloads/complete
Session\TempPathEnabled=true
Session\TempPath=/staging/downloads/incomplete
Session\TorrentExportDirectory=/staging/torrents
Session\DisableAutoTMMByDefault=false
Session\Interface=tun0
Session\InterfaceName=tun0
Session\Port=6881
Session\DiskIOType=SimplePreadPwrite
Session\BTProtocol=0
Session\Encryption=0
Session\DHTEnabled=true
Session\PeXEnabled=true
Session\GlobalMaxRatio=1.05
Session\GlobalMaxSeedingMinutes=20160
Session\ShareLimitAction=Stop
Session\QueueingSystemEnabled=true
Session\MaxActiveDownloads=6
Session\MaxActiveTorrents=-1
Session\MaxActiveUploads=-1
Session\MaxConnections=1000
Session\MaxConnectionsPerTorrent=200
Session\MaxUploads=40
Session\MaxUploadsPerTorrent=8
Session\ReannounceWhenAddressChanged=true
MergeTrackersEnabled=true
Session\LSDEnabled=false
Session\AnonymousModeEnabled=false

[Preferences]
Connection\UPnP=false
Connection\PortRangeMin=6881
Downloads\SavePath=/staging/downloads/complete/
Downloads\TempPath=/staging/downloads/incomplete/
General\Locale=en
WebUI\Enabled=true
WebUI\Address=*
WebUI\Port=8080
WebUI\HostHeaderValidation=true
WebUI\ServerDomains="@@QBITTORRENT_PUBLIC_HOST@@;gluetun"
WebUI\ReverseProxySupportEnabled=true
WebUI\TrustedReverseProxiesList="@@PROXY_A_ADDRESS@@;@@PROXY_B_ADDRESS@@"
WebUI\CSRFProtection=true
WebUI\LocalHostAuth=false
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\UseUPnP=false
WebUI\Username=admin
